# SwiftLint Configuration for Repeto

# Disabled rules (customize based on project needs)
disabled_rules:
  - trailing_whitespace

# Opt-in rules (enable additional checks)
opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - sorted_first_last
  - modifier_order
  - closure_spacing
  - operator_usage_whitespace

# Included paths
included:
  - Repeto
  - RepetoTests
  - RepetoUITests

# Excluded paths
excluded:
  - Pods
  - .build
  - build
  - DerivedData
  - fastlane

# Rule configurations
line_length:
  warning: 120
  error: 150

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - j
    - x
    - y

type_name:
  min_length: 3
  max_length: 50

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

# Custom reporter (optional)
reporter: "xcode"
